# This is a basic workflow to help you get started with Actions

name: JsonLint

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, jsonlint ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install jsonlint
        run: sudo apt install jsonlint
        
      - name: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with: 
          fileOutput: ' '

      - name: Run jsonlint against all files in the pull request
        run: |
            # Check if changed-file list exists
            if [ ! -f "$HOME/files.txt" ]; then
              echo "Changed file not list found.  Exiting."
              exit 0
            fi

            echo "Changed file list found.  Processing..."

            # only process json files
            jsonFiles=$(cat $HOME/files.txt | grep -E '.json$')
            if $jsonFiles; then
            
              # Check each file for json syntax            
              for f in $jsonFiles
              do
                echo "Checking json syntax on $f"
                jsonlint-php -v $f
              done

            fi
