# This is a basic workflow to help you get started with Actions

name: JsonLint

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with: 
          fileOutput: ' '

      - name: Install jsonlint 
        run: sudo apt install jsonlint

      - name: Run jsonlint against all files in the pull request
        run: |
          # check if file exists
          if if test -f "$HOME/files.txt"; then
            for f in $(cat $HOME/files.txt)
              do
                # Run jsonlint on each file
                if [ -n "$f" ]; then
                  jsonlint-php $f
                fi
              done          
          else
            echo "No file changes found."
          fi
