name: Parse Json File

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Required inputs
    inputs:
      customer_short_name:  # id of input
        description: 'Customer short name'
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    name: Read and parse configuration
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Checks-out a separate repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: cboroson/configuration
          path: 'configuration'
          token: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Parse Json File
        shell: pwsh
        run: |
            $config = (cat "./configuration/${{ github.event.inputs.customer_short_name }}.json" | convertFrom-json)
            foreach ($Line in $config) {
              write-output "Here"
              $Line
              # New-Item -Path "Env:VOD_$($Line.Name)" -Value $Line.Value
            }

      - name: Display results
        run: set
         
#      - name: Display results
#        shell: pwsh
#        run: |
#            $envVars = get-childItem $env: | where {$_.name -match '^VOD_.'}
#            foreach ($var in $envVars) {
#              write-output "The value for $($var.name) is $($var.value)"
#            }
