name: Parse Json File

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Required inputs
    inputs:
      customer_short_name:  # id of input
        description: 'Customer short name'
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    name: Read and parse configuration
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Checks-out a separate repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: cboroson/configuration
          path: 'configuration'
          token: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Parse Json File
        shell: pwsh
        run: ./scripts/parseConfig.ps1 -configFile "./configuration/${{ github.event.inputs.customer_short_name }}.json"
         
      - name: Display results
        shell: pwsh
        run: |
            Write-Output "We can now run terraform commands or other scripts using the configuration that is saved in"
            Write-Output "the evironment variables."
            Write-Output ""
            Write-Output "For example:
            Write-Output "terraform apply -var customer_short_name=$Env:VOD_customer_short_name"
